"""
ObservaBill Savings Scanner - Realistic Sample Data & API Fixtures

Pure Python stdlib; no external imports. Used by sample mode, tests, and UI dev.
All data structures follow explicit SavingsOpportunity and ScanResult contracts.
"""

# ============================================================================
# DATA CONTRACTS (reference implementation)
# ============================================================================
# SavingsOpportunity = dict with keys:
#   id: str
#   lever: str ("exclusion_filter" | "logs_to_metrics" | "high_cardinality_metric" | "index_quota")
#   category: str ("logs" | "metrics")
#   title: str
#   summary: str
#   monthly_savings_usd: float
#   savings_pct: str
#   effort: str ("low" | "medium" | "high")
#   confidence: str ("high" | "medium" | "low")
#   evidence: list of {label: str, volume: str, cost_usd: float}
#   generated_config: {endpoint: str, verb: str, payload: dict}
#   needs_write_scope: bool
#
# ScanResult = dict with keys:
#   total_monthly_waste_usd: float
#   currency: "USD"
#   region: str
#   opportunities: list[SavingsOpportunity] (sorted desc by monthly_savings_usd)
#   sparkline: list[float] (30 daily points)
#   notes: list[str]


# ============================================================================
# SAMPLE SCAN RESULT (6 opportunities, ~$3,500/mo total waste)
# ============================================================================

SAMPLE_SCAN = {'total_monthly_waste_usd': 1547.97,
 'currency': 'USD',
 'region': 'us',
 'price_source': 'derived',
 'scope_check': {'logs_read': True,
                 'logs_read_data': True,
                 'metrics_read': True,
                 'billing_read': False,
                 'usage_read': False,
                 'missing': ['billing_read', 'usage_read'],
                 'unlocks': {'billing_read': 'exact $ from your bill', 'usage_read': 'index quotas'}},
 'scope_gate': False,
 'sampled': True,
 'lines_examined': 2770,
 'patterns': [{'id': 'review-scaleops-process-ended-for-al',
               'lever': 'pattern_review',
               'category': 'logs',
               'service': 'scaleops',
               'status': '',
               'title': 'Review high-cost operational pattern: "process ended for already instrumented execution"',
               'summary': 'Template `process ended for already instrumented execution <NUM>` costs $322.20/mo '
                          "(15.16% of sampled logs). It's an operational log (not error/noise) — confirm it's needed "
                          'before sampling.',
               'monthly_savings_usd': 0.0,
               'monthly_cost_usd': 322.2,
               'savings_pct': '0%',
               'effort': 'low',
               'confidence': 'low',
               'evidence': [{'label': 'scaleops · template',
                             'volume': '189.5M events/mo (15.16% of sampled scaleops)',
                             'cost_usd': 322.2}],
               'generated_config': {'endpoint': '/api/v1/logs/config/indexes/main',
                                    'verb': 'PUT',
                                    'payload': {'exclusion_filters': []}},
               'needs_write_scope': False,
               'detection_query': "POST /api/v2/logs/events/search query:'*' -> mined templates -> matched process "
                                  'ended for already instrumented execution <NUM>',
               'why': 'No strong noise signal detected — kept indexed by default (conservative).',
               'why_safe': 'High-volume repeated log = 15.16% of your log bill ($322.20/mo). Not an error — confirm '
                           "it's needed; sampling it could cut most of this.",
               'template': 'process ended for already instrumented execution <NUM>',
               'sample_redacted': 'process ended for already instrumented execution 0',
               'recommended_action': 'review',
               'noise_score': 0.0,
               'metered': False,
               'monthly_events': 189530685,
               'services': [{'service': 'scaleops', 'count': 420, 'share_pct': 100.0}]},
              {'id': 'pattern-aws-no-more-objects-to',
               'lever': 'pattern_exclusion',
               'category': 'logs',
               'service': 'aws',
               'status': '',
               'title': 'Exclude noisy template: "No more objects to analyze"',
               'summary': 'Template `No more objects to analyze` accounts for 43.3% of sampled `aws` logs ≈ 541.5M '
                          'events/mo ($920.58/mo). Recommended: exclude.',
               'monthly_savings_usd': 920.58,
               'monthly_cost_usd': 920.58,
               'savings_pct': '43.3%',
               'effort': 'low',
               'confidence': 'medium',
               'evidence': [{'label': 'aws · template',
                             'volume': '541.5M events/mo (43.3% of sampled aws)',
                             'cost_usd': 920.58}],
               'generated_config': {'endpoint': '/api/v1/logs/config/indexes/main',
                                    'verb': 'PUT',
                                    'payload': {'exclusion_filters': [{'name': 'observabill-aws-no-more-objects-to',
                                                                       'filter': {'query': '"No more objects to"',
                                                                                  'sample_rate': 1.0},
                                                                       'is_enabled': True}]}},
               'needs_write_scope': True,
               'detection_query': "POST /api/v2/logs/events/search query:'service:aws' -> mined 2770 sampled msgs -> "
                                  'template matched 1200 (43.3% of sample)',
               'why': 'Safe to drop — debug-level log. Carries no unique error signal, so debugging/alerting is '
                      'unaffected.',
               'template': 'No more objects to analyze',
               'sample_redacted': 'No more objects to analyze',
               'recommended_action': 'exclude',
               'why_safe': 'Safe to drop — debug-level log. Carries no unique error signal, so debugging/alerting is '
                           'unaffected.',
               'noise_score': 0.6,
               'metered': False,
               'monthly_events': 541516245,
               'services': [{'service': 'aws', 'count': 900, 'share_pct': 75.0},
                            {'service': 'worker', 'count': 300, 'share_pct': 25.0}],
               'share_pct': 43.32,
               'cumulative_pct': 36.8},
              {'id': 'pattern-api-get-ok',
               'lever': 'pattern_exclusion',
               'category': 'logs',
               'service': 'api',
               'status': '',
               'title': 'Exclude noisy template: "GET <PATH> <NUM> ok"',
               'summary': 'Template `GET <PATH> <NUM> ok` accounts for 13.7% of sampled `api` logs ≈ 171.5M '
                          'events/mo ($291.52/mo). Recommended: exclude.',
               'monthly_savings_usd': 291.52,
               'monthly_cost_usd': 291.52,
               'savings_pct': '13.7%',
               'effort': 'low',
               'confidence': 'high',
               'evidence': [{'label': 'api · template',
                             'volume': '171.5M events/mo (13.7% of sampled api)',
                             'cost_usd': 291.52}],
               'generated_config': {'endpoint': '/api/v1/logs/config/indexes/main',
                                    'verb': 'PUT',
                                    'payload': {'exclusion_filters': [{'name': 'observabill-api-get-ok',
                                                                       'filter': {'query': '"GET ok"',
                                                                                  'sample_rate': 1.0},
                                                                       'is_enabled': True}]}},
               'needs_write_scope': True,
               'detection_query': "POST /api/v2/logs/events/search query:'service:api' -> mined 2770 sampled msgs -> "
                                  'template matched 380 (13.7% of sample)',
               'why': 'Safe to drop — health/readiness probe traffic; routine success/ack confirmation repeated at '
                      'volume. Carries no unique error signal, so debugging/alerting is unaffected.',
               'template': 'GET <PATH> <NUM> ok',
               'sample_redacted': 'GET /healthz 0 ok',
               'recommended_action': 'exclude',
               'why_safe': 'Safe to drop — health/readiness probe traffic; routine success/ack confirmation repeated '
                           'at volume. Carries no unique error signal, so debugging/alerting is unaffected.',
               'noise_score': 1.0,
               'metered': False,
               'monthly_events': 171480144,
               'services': [{'service': 'api', 'count': 380, 'share_pct': 100.0}],
               'share_pct': 13.72,
               'cumulative_pct': 61.4},
              {'id': 'pattern-worker-processed-job-completed-successfully',
               'lever': 'pattern_exclusion',
               'category': 'logs',
               'service': 'worker',
               'status': '',
               'title': 'Down-sample noisy template: "processed job <*> completed successfully"',
               'summary': 'Template `processed job <*> completed successfully` accounts for 8.7% of sampled `worker` '
                          'logs ≈ 108.3M events/mo ($184.12/mo). Recommended: sample.',
               'monthly_savings_usd': 165.71,
               'monthly_cost_usd': 184.12,
               'savings_pct': '8.7%',
               'effort': 'low',
               'confidence': 'medium',
               'evidence': [{'label': 'worker · template',
                             'volume': '108.3M events/mo (8.7% of sampled worker)',
                             'cost_usd': 184.12}],
               'generated_config': {'endpoint': '/api/v1/logs/config/indexes/main',
                                    'verb': 'PUT',
                                    'payload': {'exclusion_filters': [{'name': 'observabill-worker-processed-job-completed-successfully',
                                                                       'filter': {'query': '"processed job completed '
                                                                                           'successfully"',
                                                                                  'sample_rate': 0.9},
                                                                       'is_enabled': True}]}},
               'needs_write_scope': True,
               'detection_query': "POST /api/v2/logs/events/search query:'service:worker' -> mined 2770 sampled msgs "
                                  '-> template matched 240 (8.7% of sample)',
               'why': 'Safe to down-sample — routine success/ack confirmation repeated at volume. Carries no unique '
                      'error signal, so debugging/alerting is unaffected.',
               'template': 'processed job <*> completed successfully',
               'sample_redacted': 'processed job job-0 completed successfully',
               'recommended_action': 'sample',
               'why_safe': 'Safe to down-sample — routine success/ack confirmation repeated at volume. Carries no '
                           'unique error signal, so debugging/alerting is unaffected.',
               'noise_score': 0.5,
               'metered': False,
               'monthly_events': 108303249,
               'services': [{'service': 'worker', 'count': 240, 'share_pct': 100.0}],
               'share_pct': 8.66,
               'cumulative_pct': 68.7},
              {'id': 'pattern-py-svc-deprecationwarning-get-event-loop-is-deprecated',
               'lever': 'pattern_exclusion',
               'category': 'logs',
               'service': 'py-svc',
               'status': '',
               'title': 'Exclude noisy template: "DeprecationWarning: get_event_loop is deprecated"',
               'summary': 'Template `DeprecationWarning: get_event_loop is deprecated use <NUM>` accounts for 6.5% '
                          'of sampled `py-svc` logs ≈ 81.2M events/mo ($138.09/mo). Recommended: exclude.',
               'monthly_savings_usd': 138.09,
               'monthly_cost_usd': 138.09,
               'savings_pct': '6.5%',
               'effort': 'low',
               'confidence': 'medium',
               'evidence': [{'label': 'py-svc · template',
                             'volume': '81.2M events/mo (6.5% of sampled py-svc)',
                             'cost_usd': 138.09}],
               'generated_config': {'endpoint': '/api/v1/logs/config/indexes/main',
                                    'verb': 'PUT',
                                    'payload': {'exclusion_filters': [{'name': 'observabill-py-svc-deprecationwarning-get-event-loop-is-deprecated',
                                                                       'filter': {'query': '"DeprecationWarning: '
                                                                                           'get_event_loop is '
                                                                                           'deprecated"',
                                                                                  'sample_rate': 1.0},
                                                                       'is_enabled': True}]}},
               'needs_write_scope': True,
               'detection_query': "POST /api/v2/logs/events/search query:'service:py-svc' -> mined 2770 sampled msgs "
                                  '-> template matched 180 (6.5% of sample)',
               'why': 'Safe to drop — deprecation warning (fix at source). Carries no unique error signal, so '
                      'debugging/alerting is unaffected.',
               'template': 'DeprecationWarning: get_event_loop is deprecated use <NUM>',
               'sample_redacted': 'DeprecationWarning: get_event_loop is deprecated use 0',
               'recommended_action': 'exclude',
               'why_safe': 'Safe to drop — deprecation warning (fix at source). Carries no unique error signal, so '
                           'debugging/alerting is unaffected.',
               'noise_score': 0.5,
               'metered': False,
               'monthly_events': 81227436,
               'services': [{'service': 'py-svc', 'count': 180, 'share_pct': 100.0}],
               'share_pct': 6.5,
               'cumulative_pct': 74.3}],
 'pattern_leaderboard': [{'template': 'No more objects to analyze',
                          'count': 1200,
                          'services': [{'service': 'aws', 'count': 900, 'share_pct': 75.0},
                                       {'service': 'worker', 'count': 300, 'share_pct': 25.0}],
                          'hosts': ['h1', 'h2'],
                          'status_breakdown': {'debug': 1200},
                          'sample_redacted': 'No more objects to analyze',
                          'monthly_events': 541516245,
                          'monthly_cost_usd': 920.58,
                          'share_pct': 43.32,
                          'cumulative_pct': 36.8,
                          'classification': {'is_noise': True,
                                             'recommendation': 'exclude',
                                             'confidence': 'medium',
                                             'why_safe': 'Safe to drop — debug-level log. Carries no unique error '
                                                         'signal, so debugging/alerting is unaffected.',
                                             'noise_score': 0.6,
                                             'metered': False,
                                             'signal': 'noise'},
                          'recommended_action': 'exclude'},
                         {'template': 'process ended for already instrumented execution <NUM>',
                          'count': 420,
                          'services': [{'service': 'scaleops', 'count': 420, 'share_pct': 100.0}],
                          'hosts': ['h4'],
                          'status_breakdown': {'info': 420},
                          'sample_redacted': 'process ended for already instrumented execution 0',
                          'monthly_events': 189530685,
                          'monthly_cost_usd': 322.2,
                          'share_pct': 15.16,
                          'cumulative_pct': 49.7,
                          'classification': {'is_noise': False,
                                             'recommendation': 'keep',
                                             'confidence': 'high',
                                             'why_safe': 'No strong noise signal detected — kept indexed by default '
                                                         '(conservative).',
                                             'noise_score': 0.0,
                                             'metered': False,
                                             'signal': 'neutral'},
                          'recommended_action': 'review'},
                         {'template': 'GET <PATH> <NUM> ok',
                          'count': 380,
                          'services': [{'service': 'api', 'count': 380, 'share_pct': 100.0}],
                          'hosts': ['h3'],
                          'status_breakdown': {'info': 380},
                          'sample_redacted': 'GET /healthz 0 ok',
                          'monthly_events': 171480144,
                          'monthly_cost_usd': 291.52,
                          'share_pct': 13.72,
                          'cumulative_pct': 61.4,
                          'classification': {'is_noise': True,
                                             'recommendation': 'exclude',
                                             'confidence': 'high',
                                             'why_safe': 'Safe to drop — health/readiness probe traffic; routine '
                                                         'success/ack confirmation repeated at volume. Carries no '
                                                         'unique error signal, so debugging/alerting is unaffected.',
                                             'noise_score': 1.0,
                                             'metered': False,
                                             'signal': 'noise'},
                          'recommended_action': 'exclude'},
                         {'template': 'processed job <*> completed successfully',
                          'count': 240,
                          'services': [{'service': 'worker', 'count': 240, 'share_pct': 100.0}],
                          'hosts': ['h5'],
                          'status_breakdown': {'info': 240},
                          'sample_redacted': 'processed job job-0 completed successfully',
                          'monthly_events': 108303249,
                          'monthly_cost_usd': 184.12,
                          'share_pct': 8.66,
                          'cumulative_pct': 68.7,
                          'classification': {'is_noise': True,
                                             'recommendation': 'sample',
                                             'confidence': 'medium',
                                             'why_safe': 'Safe to down-sample — routine success/ack confirmation '
                                                         'repeated at volume. Carries no unique error signal, so '
                                                         'debugging/alerting is unaffected.',
                                             'noise_score': 0.5,
                                             'metered': False,
                                             'signal': 'noise'},
                          'recommended_action': 'sample'},
                         {'template': 'DeprecationWarning: get_event_loop is deprecated use <NUM>',
                          'count': 180,
                          'services': [{'service': 'py-svc', 'count': 180, 'share_pct': 100.0}],
                          'hosts': ['h6'],
                          'status_breakdown': {'warn': 180},
                          'sample_redacted': 'DeprecationWarning: get_event_loop is deprecated use 0',
                          'monthly_events': 81227436,
                          'monthly_cost_usd': 138.09,
                          'share_pct': 6.5,
                          'cumulative_pct': 74.3,
                          'classification': {'is_noise': True,
                                             'recommendation': 'exclude',
                                             'confidence': 'medium',
                                             'why_safe': 'Safe to drop — deprecation warning (fix at source). '
                                                         'Carries no unique error signal, so debugging/alerting is '
                                                         'unaffected.',
                                             'noise_score': 0.5,
                                             'metered': False,
                                             'signal': 'noise'},
                          'recommended_action': 'exclude'},
                         {'template': 'ERROR failed to connect to database connection refused <NUM>',
                          'count': 120,
                          'services': [{'service': 'api', 'count': 120, 'share_pct': 100.0}],
                          'hosts': ['h7'],
                          'status_breakdown': {'error': 120},
                          'sample_redacted': 'ERROR failed to connect to database connection refused 0',
                          'monthly_events': 54151624,
                          'monthly_cost_usd': 92.06,
                          'share_pct': 4.33,
                          'cumulative_pct': 77.9,
                          'classification': {'is_noise': False,
                                             'recommendation': 'keep',
                                             'confidence': 'high',
                                             'why_safe': 'Contains error/failure signal — keep indexed for debugging '
                                                         'and alerting.',
                                             'noise_score': 0.0,
                                             'metered': False,
                                             'signal': 'error'},
                          'recommended_action': 'keep'},
                         {'template': 'retry attempt <NUM> for queue orders processing',
                          'count': 120,
                          'services': [{'service': 'q1', 'count': 120, 'share_pct': 100.0}],
                          'hosts': ['h8'],
                          'status_breakdown': {'info': 120},
                          'sample_redacted': 'retry attempt 0 for queue orders processing',
                          'monthly_events': 54151624,
                          'monthly_cost_usd': 92.06,
                          'share_pct': 4.33,
                          'cumulative_pct': 81.6,
                          'classification': {'is_noise': False,
                                             'recommendation': 'keep',
                                             'confidence': 'high',
                                             'why_safe': 'No strong noise signal detected — kept indexed by default '
                                                         '(conservative).',
                                             'noise_score': 0.0,
                                             'metered': False,
                                             'signal': 'neutral'},
                          'recommended_action': 'keep'},
                         {'template': 'retry attempt <NUM> for queue orders processing backoff',
                          'count': 110,
                          'services': [{'service': 'q2', 'count': 110, 'share_pct': 100.0}],
                          'hosts': ['h9'],
                          'status_breakdown': {'info': 110},
                          'sample_redacted': 'retry attempt 0 for queue orders processing backoff',
                          'monthly_events': 49638989,
                          'monthly_cost_usd': 84.39,
                          'share_pct': 3.97,
                          'cumulative_pct': 85.0,
                          'classification': {'is_noise': False,
                                             'recommendation': 'keep',
                                             'confidence': 'high',
                                             'why_safe': 'No strong noise signal detected — kept indexed by default '
                                                         '(conservative).',
                                             'noise_score': 0.0,
                                             'metered': False,
                                             'signal': 'neutral'},
                          'recommended_action': 'keep'}],
 'similar_families': [{'family_terms': ['attempt', 'for', 'orders', 'processing', 'queue', 'retry'],
                       'members': [{'template': 'retry attempt <NUM> for queue orders processing',
                                    'count': 120,
                                    'services': [{'service': 'q1', 'count': 120, 'share_pct': 100.0}],
                                    'hosts': ['h8'],
                                    'status_breakdown': {'info': 120},
                                    'sample_redacted': 'retry attempt 0 for queue orders processing',
                                    'monthly_events': 54151624,
                                    'monthly_cost_usd': 92.06,
                                    'share_pct': 4.33,
                                    'cumulative_pct': 81.6,
                                    'classification': {'is_noise': False,
                                                       'recommendation': 'keep',
                                                       'confidence': 'high',
                                                       'why_safe': 'No strong noise signal detected — kept indexed '
                                                                   'by default (conservative).',
                                                       'noise_score': 0.0,
                                                       'metered': False,
                                                       'signal': 'neutral'},
                                    'recommended_action': 'keep'},
                                   {'template': 'retry attempt <NUM> for queue orders processing backoff',
                                    'count': 110,
                                    'services': [{'service': 'q2', 'count': 110, 'share_pct': 100.0}],
                                    'hosts': ['h9'],
                                    'status_breakdown': {'info': 110},
                                    'sample_redacted': 'retry attempt 0 for queue orders processing backoff',
                                    'monthly_events': 49638989,
                                    'monthly_cost_usd': 84.39,
                                    'share_pct': 3.97,
                                    'cumulative_pct': 85.0,
                                    'classification': {'is_noise': False,
                                                       'recommendation': 'keep',
                                                       'confidence': 'high',
                                                       'why_safe': 'No strong noise signal detected — kept indexed '
                                                                   'by default (conservative).',
                                                       'noise_score': 0.0,
                                                       'metered': False,
                                                       'signal': 'neutral'},
                                    'recommended_action': 'keep'}],
                       'member_count': 2,
                       'combined_monthly_cost_usd': 176.45,
                       'combined_query': '"retry attempt for queue" OR "retry attempt for queue"'}],
 'surges': [{'kind': 'level_shift',
             'series': 'aws',
             'ratio': 1.5,
             'baseline_mean': 8000000,
             'recent_mean': 12000000,
             'onset_date': '2026-07-18',
             'monthly_excess_events': 120000000,
             'severity': 120000000,
             'monthly_cost_usd': 204.0},
            {'kind': 'new_pattern',
             'series': 'checkout-svc',
             'onset_index': 10,
             'onset_date': '2026-07-11',
             'recent_daily_avg': 0,
             'monthly_events': 0,
             'severity': 0,
             'monthly_cost_usd': 0.0}],
 'anomalies': [{'kind': 'level_shift',
                'series': 'aws',
                'ratio': 1.5,
                'baseline_mean': 8000000,
                'recent_mean': 12000000,
                'onset_date': '2026-07-18',
                'monthly_excess_events': 120000000,
                'severity': 120000000,
                'monthly_cost_usd': 204.0},
               {'kind': 'new_pattern',
                'series': 'checkout-svc',
                'onset_index': 10,
                'onset_date': '2026-07-11',
                'recent_daily_avg': 0,
                'monthly_events': 0,
                'severity': 0,
                'monthly_cost_usd': 0.0}],
 'bill_share_pct': 85.0,
 'opportunities': [{'id': 'pattern-aws-no-more-objects-to',
                    'lever': 'pattern_exclusion',
                    'category': 'logs',
                    'service': 'aws',
                    'status': '',
                    'title': 'Exclude noisy template: "No more objects to analyze"',
                    'summary': 'Template `No more objects to analyze` accounts for 43.3% of sampled `aws` logs ≈ '
                               '541.5M events/mo ($920.58/mo). Recommended: exclude.',
                    'monthly_savings_usd': 920.58,
                    'monthly_cost_usd': 920.58,
                    'savings_pct': '43.3%',
                    'effort': 'low',
                    'confidence': 'medium',
                    'evidence': [{'label': 'aws · template',
                                  'volume': '541.5M events/mo (43.3% of sampled aws)',
                                  'cost_usd': 920.58}],
                    'generated_config': {'endpoint': '/api/v1/logs/config/indexes/main',
                                         'verb': 'PUT',
                                         'payload': {'exclusion_filters': [{'name': 'observabill-aws-no-more-objects-to',
                                                                            'filter': {'query': '"No more objects '
                                                                                                'to"',
                                                                                       'sample_rate': 1.0},
                                                                            'is_enabled': True}]}},
                    'needs_write_scope': True,
                    'detection_query': "POST /api/v2/logs/events/search query:'service:aws' -> mined 2770 sampled "
                                       'msgs -> template matched 1200 (43.3% of sample)',
                    'why': 'Safe to drop — debug-level log. Carries no unique error signal, so debugging/alerting is '
                           'unaffected.',
                    'template': 'No more objects to analyze',
                    'sample_redacted': 'No more objects to analyze',
                    'recommended_action': 'exclude',
                    'why_safe': 'Safe to drop — debug-level log. Carries no unique error signal, so '
                                'debugging/alerting is unaffected.',
                    'noise_score': 0.6,
                    'metered': False,
                    'monthly_events': 541516245,
                    'services': [{'service': 'aws', 'count': 900, 'share_pct': 75.0},
                                 {'service': 'worker', 'count': 300, 'share_pct': 25.0}],
                    'share_pct': 43.32,
                    'cumulative_pct': 36.8},
                   {'id': 'pattern-api-get-ok',
                    'lever': 'pattern_exclusion',
                    'category': 'logs',
                    'service': 'api',
                    'status': '',
                    'title': 'Exclude noisy template: "GET <PATH> <NUM> ok"',
                    'summary': 'Template `GET <PATH> <NUM> ok` accounts for 13.7% of sampled `api` logs ≈ 171.5M '
                               'events/mo ($291.52/mo). Recommended: exclude.',
                    'monthly_savings_usd': 291.52,
                    'monthly_cost_usd': 291.52,
                    'savings_pct': '13.7%',
                    'effort': 'low',
                    'confidence': 'high',
                    'evidence': [{'label': 'api · template',
                                  'volume': '171.5M events/mo (13.7% of sampled api)',
                                  'cost_usd': 291.52}],
                    'generated_config': {'endpoint': '/api/v1/logs/config/indexes/main',
                                         'verb': 'PUT',
                                         'payload': {'exclusion_filters': [{'name': 'observabill-api-get-ok',
                                                                            'filter': {'query': '"GET ok"',
                                                                                       'sample_rate': 1.0},
                                                                            'is_enabled': True}]}},
                    'needs_write_scope': True,
                    'detection_query': "POST /api/v2/logs/events/search query:'service:api' -> mined 2770 sampled "
                                       'msgs -> template matched 380 (13.7% of sample)',
                    'why': 'Safe to drop — health/readiness probe traffic; routine success/ack confirmation repeated '
                           'at volume. Carries no unique error signal, so debugging/alerting is unaffected.',
                    'template': 'GET <PATH> <NUM> ok',
                    'sample_redacted': 'GET /healthz 0 ok',
                    'recommended_action': 'exclude',
                    'why_safe': 'Safe to drop — health/readiness probe traffic; routine success/ack confirmation '
                                'repeated at volume. Carries no unique error signal, so debugging/alerting is '
                                'unaffected.',
                    'noise_score': 1.0,
                    'metered': False,
                    'monthly_events': 171480144,
                    'services': [{'service': 'api', 'count': 380, 'share_pct': 100.0}],
                    'share_pct': 13.72,
                    'cumulative_pct': 61.4},
                   {'id': 'pattern-worker-processed-job-completed-successfully',
                    'lever': 'pattern_exclusion',
                    'category': 'logs',
                    'service': 'worker',
                    'status': '',
                    'title': 'Down-sample noisy template: "processed job <*> completed successfully"',
                    'summary': 'Template `processed job <*> completed successfully` accounts for 8.7% of sampled '
                               '`worker` logs ≈ 108.3M events/mo ($184.12/mo). Recommended: sample.',
                    'monthly_savings_usd': 165.71,
                    'monthly_cost_usd': 184.12,
                    'savings_pct': '8.7%',
                    'effort': 'low',
                    'confidence': 'medium',
                    'evidence': [{'label': 'worker · template',
                                  'volume': '108.3M events/mo (8.7% of sampled worker)',
                                  'cost_usd': 184.12}],
                    'generated_config': {'endpoint': '/api/v1/logs/config/indexes/main',
                                         'verb': 'PUT',
                                         'payload': {'exclusion_filters': [{'name': 'observabill-worker-processed-job-completed-successfully',
                                                                            'filter': {'query': '"processed job '
                                                                                                'completed '
                                                                                                'successfully"',
                                                                                       'sample_rate': 0.9},
                                                                            'is_enabled': True}]}},
                    'needs_write_scope': True,
                    'detection_query': "POST /api/v2/logs/events/search query:'service:worker' -> mined 2770 sampled "
                                       'msgs -> template matched 240 (8.7% of sample)',
                    'why': 'Safe to down-sample — routine success/ack confirmation repeated at volume. Carries no '
                           'unique error signal, so debugging/alerting is unaffected.',
                    'template': 'processed job <*> completed successfully',
                    'sample_redacted': 'processed job job-0 completed successfully',
                    'recommended_action': 'sample',
                    'why_safe': 'Safe to down-sample — routine success/ack confirmation repeated at volume. Carries '
                                'no unique error signal, so debugging/alerting is unaffected.',
                    'noise_score': 0.5,
                    'metered': False,
                    'monthly_events': 108303249,
                    'services': [{'service': 'worker', 'count': 240, 'share_pct': 100.0}],
                    'share_pct': 8.66,
                    'cumulative_pct': 68.7},
                   {'id': 'pattern-py-svc-deprecationwarning-get-event-loop-is-deprecated',
                    'lever': 'pattern_exclusion',
                    'category': 'logs',
                    'service': 'py-svc',
                    'status': '',
                    'title': 'Exclude noisy template: "DeprecationWarning: get_event_loop is deprecated"',
                    'summary': 'Template `DeprecationWarning: get_event_loop is deprecated use <NUM>` accounts for '
                               '6.5% of sampled `py-svc` logs ≈ 81.2M events/mo ($138.09/mo). Recommended: exclude.',
                    'monthly_savings_usd': 138.09,
                    'monthly_cost_usd': 138.09,
                    'savings_pct': '6.5%',
                    'effort': 'low',
                    'confidence': 'medium',
                    'evidence': [{'label': 'py-svc · template',
                                  'volume': '81.2M events/mo (6.5% of sampled py-svc)',
                                  'cost_usd': 138.09}],
                    'generated_config': {'endpoint': '/api/v1/logs/config/indexes/main',
                                         'verb': 'PUT',
                                         'payload': {'exclusion_filters': [{'name': 'observabill-py-svc-deprecationwarning-get-event-loop-is-deprecated',
                                                                            'filter': {'query': '"DeprecationWarning: '
                                                                                                'get_event_loop is '
                                                                                                'deprecated"',
                                                                                       'sample_rate': 1.0},
                                                                            'is_enabled': True}]}},
                    'needs_write_scope': True,
                    'detection_query': "POST /api/v2/logs/events/search query:'service:py-svc' -> mined 2770 sampled "
                                       'msgs -> template matched 180 (6.5% of sample)',
                    'why': 'Safe to drop — deprecation warning (fix at source). Carries no unique error signal, so '
                           'debugging/alerting is unaffected.',
                    'template': 'DeprecationWarning: get_event_loop is deprecated use <NUM>',
                    'sample_redacted': 'DeprecationWarning: get_event_loop is deprecated use 0',
                    'recommended_action': 'exclude',
                    'why_safe': 'Safe to drop — deprecation warning (fix at source). Carries no unique error signal, '
                                'so debugging/alerting is unaffected.',
                    'noise_score': 0.5,
                    'metered': False,
                    'monthly_events': 81227436,
                    'services': [{'service': 'py-svc', 'count': 180, 'share_pct': 100.0}],
                    'share_pct': 6.5,
                    'cumulative_pct': 74.3},
                   {'id': 'field_bloat:trace_stack',
                    'lever': 'field_bloat',
                    'category': 'logs',
                    'service': '',
                    'title': 'Trim bloated field `trace_stack`',
                    'summary': 'Field `trace_stack` averages 1600 bytes and appears in 100% of sampled events — '
                               'trimming it via a log pipeline remap/remove reduces ingested GB.',
                    'monthly_savings_usd': 32.0,
                    'monthly_cost_usd': 32.0,
                    'savings_pct': 'ingest-reduction',
                    'effort': 'medium',
                    'confidence': 'medium',
                    'evidence': [{'label': 'trace_stack',
                                  'volume': '1600 bytes avg · 100% of events',
                                  'cost_usd': 32.0}],
                    'generated_config': {'endpoint': '/api/v1/logs/config/pipelines',
                                         'verb': 'POST',
                                         'payload': {'name': 'observabill-trim-trace_stack',
                                                     'filter': {'query': '*'},
                                                     'processors': [{'type': 'string-builder-processor',
                                                                     'sources': ['trace_stack'],
                                                                     'is_enabled': True,
                                                                     'note': 'remove/shorten this large '
                                                                             'attribute'}]}},
                    'needs_write_scope': True,
                    'detection_query': 'sampled events → field `trace_stack` flagged as large_field',
                    'why': 'Field `trace_stack` averages 1600 bytes and appears in 100% of sampled events — trimming '
                           'it via a log pipeline remap/remove reduces ingested GB.',
                    'why_safe': 'Field `trace_stack` averages 1600 bytes and appears in 100% of sampled events — '
                                'trimming it via a log pipeline remap/remove reduces ingested GB.',
                    'recommended_action': 'trim_fields',
                    'field_name': 'trace_stack',
                    'cardinality': 1},
                   {'id': 'field_bloat:request_id',
                    'lever': 'field_bloat',
                    'category': 'logs',
                    'service': '',
                    'title': 'Reduce cardinality of bloated field `request_id`',
                    'summary': 'Field `request_id` has ~300 distinct values across 300 events (100% unique) — '
                               'near-unbounded cardinality bloats indexing and any facet on it; drop or hash it.',
                    'monthly_savings_usd': 0.07,
                    'monthly_cost_usd': 0.07,
                    'savings_pct': 'ingest-reduction',
                    'effort': 'medium',
                    'confidence': 'medium',
                    'evidence': [{'label': 'request_id',
                                  'volume': '300 distinct values (100% unique)',
                                  'cost_usd': 0.07}],
                    'generated_config': {'endpoint': '/api/v1/logs/config/pipelines',
                                         'verb': 'POST',
                                         'payload': {'name': 'observabill-trim-request_id',
                                                     'filter': {'query': '*'},
                                                     'processors': [{'type': 'attribute-remapper',
                                                                     'sources': ['request_id'],
                                                                     'is_enabled': True,
                                                                     'note': 'hash or drop this attribute to cut '
                                                                             'cardinality'}]}},
                    'needs_write_scope': True,
                    'detection_query': 'sampled events → field `request_id` flagged as high_cardinality',
                    'why': 'Field `request_id` has ~300 distinct values across 300 events (100% unique) — '
                           'near-unbounded cardinality bloats indexing and any facet on it; drop or hash it.',
                    'why_safe': 'Field `request_id` has ~300 distinct values across 300 events (100% unique) — '
                                'near-unbounded cardinality bloats indexing and any facet on it; drop or hash it.',
                    'recommended_action': 'reduce_cardinality',
                    'field_name': 'request_id',
                    'cardinality': 300},
                   {'id': 'review-scaleops-process-ended-for-al',
                    'lever': 'pattern_review',
                    'category': 'logs',
                    'service': 'scaleops',
                    'status': '',
                    'title': 'Review high-cost operational pattern: "process ended for already instrumented '
                             'execution"',
                    'summary': 'Template `process ended for already instrumented execution <NUM>` costs $322.20/mo '
                               "(15.16% of sampled logs). It's an operational log (not error/noise) — confirm it's "
                               'needed before sampling.',
                    'monthly_savings_usd': 0.0,
                    'monthly_cost_usd': 322.2,
                    'savings_pct': '0%',
                    'effort': 'low',
                    'confidence': 'low',
                    'evidence': [{'label': 'scaleops · template',
                                  'volume': '189.5M events/mo (15.16% of sampled scaleops)',
                                  'cost_usd': 322.2}],
                    'generated_config': {'endpoint': '/api/v1/logs/config/indexes/main',
                                         'verb': 'PUT',
                                         'payload': {'exclusion_filters': []}},
                    'needs_write_scope': False,
                    'detection_query': "POST /api/v2/logs/events/search query:'*' -> mined templates -> matched "
                                       'process ended for already instrumented execution <NUM>',
                    'why': 'No strong noise signal detected — kept indexed by default (conservative).',
                    'why_safe': 'High-volume repeated log = 15.16% of your log bill ($322.20/mo). Not an error — '
                                "confirm it's needed; sampling it could cut most of this.",
                    'template': 'process ended for already instrumented execution <NUM>',
                    'sample_redacted': 'process ended for already instrumented execution 0',
                    'recommended_action': 'review',
                    'noise_score': 0.0,
                    'metered': False,
                    'monthly_events': 189530685,
                    'services': [{'service': 'scaleops', 'count': 420, 'share_pct': 100.0}]}],
 'field_bloat': [{'field_name': 'trace_stack',
                  'kind': 'large_field',
                  'frequency': 1.0,
                  'avg_bytes': 1600.0,
                  'cardinality': 1,
                  'cardinality_ratio': 0.003,
                  'recommendation': 'trim_fields',
                  'why_safe': 'Field `trace_stack` averages 1600 bytes and appears in 100% of sampled events — '
                              'trimming it via a log pipeline remap/remove reduces ingested GB.',
                  'impact': 1600.0},
                 {'field_name': 'request_id',
                  'kind': 'high_cardinality',
                  'frequency': 1.0,
                  'avg_bytes': 3.6,
                  'cardinality': 300,
                  'cardinality_ratio': 1.0,
                  'recommendation': 'reduce_cardinality',
                  'why_safe': 'Field `request_id` has ~300 distinct values across 300 events (100% unique) — '
                              'near-unbounded cardinality bloats indexing and any facet on it; drop or hash it.',
                  'impact': 3.6333333333333333}],
 'sparkline': [4.1,
               4.2,
               4.0,
               4.3,
               4.15,
               4.05,
               4.2,
               4.25,
               4.1,
               4.0,
               4.3,
               4.2,
               4.1,
               4.05,
               4.15,
               4.2,
               4.3,
               4.25,
               4.1,
               4.2,
               4.15,
               4.05,
               4.2,
               4.3,
               4.25,
               4.1,
               4.2,
               4.3,
               4.5,
               4.8],
 'notes': ['Examined 2770 sampled log lines account-wide (representative, not exhaustive).'],
 'log_cost_map': [{'service': 'aws',
                   'status': 'debug',
                   'monthly_events': 1071428571,
                   'monthly_cost_usd': 1821.43,
                   'share_pct': 70.62},
                  {'service': 'scaleops',
                   'status': 'info',
                   'monthly_events': 222857142,
                   'monthly_cost_usd': 378.86,
                   'share_pct': 14.69},
                  {'service': 'worker',
                   'status': 'info',
                   'monthly_events': 171428571,
                   'monthly_cost_usd': 291.43,
                   'share_pct': 11.3},
                  {'service': 'api',
                   'status': 'error',
                   'monthly_events': 51428571,
                   'monthly_cost_usd': 87.43,
                   'share_pct': 3.39}],
 'log_total_monthly_cost_usd': 2579.15}


LOGS_AGGREGATE_RESP = {
    "data": {
        "buckets": [
            {
                "by": {"service": "cdn-prod", "status": "200"},
                "computes": {"_sample_bucket_count": 18500000},
            },
            {
                "by": {"service": "load-balancer-us", "status": "200"},
                "computes": {"_sample_bucket_count": 8200000},
            },
            {
                "by": {"service": "api-gateway-prod", "status": "200"},
                "computes": {"_sample_bucket_count": 5100000},
            },
            {
                "by": {"service": "cdn-edge-cache", "status": "200"},
                "computes": {"_sample_bucket_count": 3800000},
            },
            {
                "by": {"service": "api-gateway-prod", "status": "401"},
                "computes": {"_sample_bucket_count": 450000},
            },
            {
                "by": {"service": "worker-service", "level": "DEBUG"},
                "computes": {"_sample_bucket_count": 6700000},
            },
            {
                "by": {"service": "scheduler", "level": "DEBUG"},
                "computes": {"_sample_bucket_count": 2900000},
            },
            {
                "by": {"service": "payment-service", "event": "transaction.initiated"},
                "computes": {"_sample_bucket_count": 2300000},
            },
        ],
        "meta": {
            "page": {"after": None},
            "status": "done",
        },
    },
}


# Metrics response: payment.transaction.latency with exploding user_id cardinality
METRICS_VOLUMES_RESP = {
    "data": [
        {
            "attributes": {
                "archived": False,
                "description": "Payment transaction latency tracked per user",
                "distinct_count": 450000,
                "metric_type": "gauge",
                "tags": [
                    "env:production",
                    "service:payment-service",
                    "user_id",
                    "endpoint",
                    "status",
                ],
                "unit": {
                    "family": "time",
                    "name": "millisecond",
                    "short_name": "ms",
                },
            },
            "id": "payment.transaction.latency",
            "type": "metrics",
        }
    ],
    "included": [
        {
            "attributes": {
                "cardinality": 450000,
                "percentile_approx": 1250,
                "tag_name": "user_id",
            },
            "id": "payment.transaction.latency:user_id",
            "type": "metric_tag_configuration",
        },
        {
            "attributes": {
                "cardinality": 12,
                "percentile_approx": 125,
                "tag_name": "endpoint",
            },
            "id": "payment.transaction.latency:endpoint",
            "type": "metric_tag_configuration",
        },
    ],
}


# Usage/ingestion response: 30-day daily log volumes (matches sparkline)
USAGE_LOGS_RESP = {
    "usage": [
        {
            "date": "2025-06-10",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2150000,
            "logs_ingested_bytes": 5420000000,
        },
        {
            "date": "2025-06-11",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2155000,
            "logs_ingested_bytes": 5430000000,
        },
        {
            "date": "2025-06-12",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2160000,
            "logs_ingested_bytes": 5440000000,
        },
        {
            "date": "2025-06-13",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2175000,
            "logs_ingested_bytes": 5470000000,
        },
        {
            "date": "2025-06-14",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2180000,
            "logs_ingested_bytes": 5480000000,
        },
        {
            "date": "2025-06-15",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2165000,
            "logs_ingested_bytes": 5450000000,
        },
        {
            "date": "2025-06-16",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2170000,
            "logs_ingested_bytes": 5460000000,
        },
        {
            "date": "2025-06-17",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2185000,
            "logs_ingested_bytes": 5490000000,
        },
        {
            "date": "2025-06-18",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2190000,
            "logs_ingested_bytes": 5500000000,
        },
        {
            "date": "2025-06-19",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2195000,
            "logs_ingested_bytes": 5510000000,
        },
        {
            "date": "2025-06-20",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2210000,
            "logs_ingested_bytes": 5540000000,
        },
        {
            "date": "2025-06-21",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2215000,
            "logs_ingested_bytes": 5550000000,
        },
        {
            "date": "2025-06-22",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2220000,
            "logs_ingested_bytes": 5560000000,
        },
        {
            "date": "2025-06-23",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2225000,
            "logs_ingested_bytes": 5570000000,
        },
        {
            "date": "2025-06-24",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2235000,
            "logs_ingested_bytes": 5590000000,
        },
        {
            "date": "2025-06-25",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2240000,
            "logs_ingested_bytes": 5600000000,
        },
        {
            "date": "2025-06-26",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2250000,
            "logs_ingested_bytes": 5620000000,
        },
        {
            "date": "2025-06-27",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2260000,
            "logs_ingested_bytes": 5640000000,
        },
        {
            "date": "2025-06-28",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2270000,
            "logs_ingested_bytes": 5660000000,
        },
        {
            "date": "2025-06-29",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2280000,
            "logs_ingested_bytes": 5680000000,
        },
        {
            "date": "2025-06-30",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2290000,
            "logs_ingested_bytes": 5700000000,
        },
        {
            "date": "2025-07-01",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2295000,
            "logs_ingested_bytes": 5710000000,
        },
        {
            "date": "2025-07-02",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2310000,
            "logs_ingested_bytes": 5740000000,
        },
        {
            "date": "2025-07-03",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2330000,
            "logs_ingested_bytes": 5780000000,
        },
        {
            "date": "2025-07-04",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2350000,
            "logs_ingested_bytes": 5820000000,
        },
        {
            "date": "2025-07-05",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2375000,
            "logs_ingested_bytes": 5870000000,
        },
        {
            "date": "2025-07-06",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2395000,
            "logs_ingested_bytes": 5910000000,
        },
        {
            "date": "2025-07-07",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2420000,
            "logs_ingested_bytes": 5960000000,
        },
        {
            "date": "2025-07-08",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2500000,
            "logs_ingested_bytes": 6130000000,
        },
        {
            "date": "2025-07-09",
            "org_name": "revenue-staging",
            "public_id": "org123456",
            "logs_indexed_events": 2480000,
            "logs_ingested_bytes": 6090000000,
        },
    ]
}


# Indexes configuration response: main index with existing exclusion filters
INDEXES_RESP = {
    "indexes": [
        {
            "name": "main",
            "num_retention_days": 30,
            "daily_limit": 500,
            "is_rate_limited": False,
            "notification_threshold_pct": None,
            "exclusion_filters": [
                {
                    "name": "exclude-synthetics",
                    "filter": "source:synthetics",
                    "num_matching_logs": 1200000,
                }
            ],
        },
        {
            "name": "sensitive-data",
            "num_retention_days": 90,
            "daily_limit": 100,
            "is_rate_limited": False,
            "notification_threshold_pct": None,
            "exclusion_filters": [],
        },
    ]
}


# ============================================================================
# INTERNAL VALIDATION (data consistency checks)
# ============================================================================


def _validate_sample_scan():
    """Validate that SAMPLE_SCAN is internally consistent (v2 content-intelligence contract)."""
    total_opportunities = 0.0

    for opp in SAMPLE_SCAN["opportunities"]:
        total_opportunities += opp["monthly_savings_usd"]
        # v2: realized savings must never exceed the full monthly cost of the pattern.
        full_cost = opp.get("monthly_cost_usd", opp["monthly_savings_usd"])
        assert (
            opp["monthly_savings_usd"] <= full_cost + 0.01
        ), f"{opp['id']}: realized savings ${opp['monthly_savings_usd']:.2f} > full cost ${full_cost:.2f}"
        # every pattern/field opportunity must carry a safety rationale.
        assert opp.get("why_safe"), f"{opp['id']}: missing why_safe"

    assert (
        abs(total_opportunities - SAMPLE_SCAN["total_monthly_waste_usd"]) < 1.0
    ), f"Opportunities sum ${total_opportunities:.0f} != scan total ${SAMPLE_SCAN['total_monthly_waste_usd']:.0f}"

    assert (
        len(SAMPLE_SCAN["sparkline"]) == 30
    ), f"Sparkline has {len(SAMPLE_SCAN['sparkline'])} points, expected 30"

    savings = [opp["monthly_savings_usd"] for opp in SAMPLE_SCAN["opportunities"]]
    assert savings == sorted(savings, reverse=True), "Opportunities not sorted by savings (descending)"

    # v3 pattern-first surfaces present
    for key in ("patterns", "pattern_leaderboard", "similar_families", "surges",
                "bill_share_pct", "scope_gate", "field_bloat", "lines_examined", "sampled"):
        assert key in SAMPLE_SCAN, f"SAMPLE_SCAN missing v3 key: {key}"
    # leaderboard rows carry a recommended_action + cumulative_pct
    for row in SAMPLE_SCAN["pattern_leaderboard"]:
        assert "recommended_action" in row and "cumulative_pct" in row


_validate_sample_scan()
